version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: db-postgres:0.1
    volumes:
      - ~/Codes/YaBlog/DockerVolume/YaDjangoBlog/PostgreSQL/data:/var/lib/postgresql/data
      - ~/Codes/YaBlog/DockerVolume/YaDjangoBlog/Backups:/backups
    env_file: .env.dev
    ports:
      - "5432:35432"

  rabbitmq:
    image: rabbitmq:3.6.15
    env_file: .env.dev
    ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"

  redis:
    image: redis:3.2.0
    command: redis-server --requirepass 'RD@123456'
    ports:
      - '6379:6379'
    volumes:
      - ~/Codes/YaBlog/DockerVolume/YaDjangoBlog/Redis/data:/data
    env_file: .env.dev

  elasticsearch:
    image: base-elasticsearch:0.1
    ports:
      - '9200:9200'
      - '9100:9100'

  django:
    image: base-django:0.1
    command: /start-dev.sh
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mailhog
      - elasticsearch
    volumes:
      - .:/webapp
    ports:
      - "8000:8000"
    env_file: .env.dev

  pycharm:
    image: base-django:0.1
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mailhog
      - elasticsearch
    volumes:
      - .:/webapp
    env_file: .env.dev

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  celeryworker:
    image: base-django:0.1
    command: /start-celeryworker.sh
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mailhog
      - elasticsearch
    volumes:
      - .:/webapp
    env_file: .env.dev

  celerybeat:
    image: base-django:0.1
    command: /start-celerybeat.sh
    volumes:
      - .:/webapp
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - mailhog
      - elasticsearch
    env_file: .env.dev

  celeryflower:
    image: base-django:0.1
    command: /start-celeryflower.sh
    volumes:
      - .:/webapp
    depends_on:
      - rabbitmq
      - redis
    env_file: .env.dev
    ports:
      - "5555:5555"
