version: "3.7"

x-playbase-common:
  &playbase-common
  image: playbase:local
  volumes:
    - .:/opt/playbase
  environment:
    &playbase-common-env
    DJANGO_SECRET_KEY: @ZF8dr8z@L*asd3oR?R/pe1}|l12enem(ppFV=U<!F@lF-k9wE

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./compose/postgres/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./.volume/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  elasticsearch:
    image: elasticsearch:local
    ports:
      - '9200:9200'
      - '9100:9100'

  playbase-web:
    <<: *playbase-common
    command: ["playbase-cli", "webserver"]
    ports:
      - "8000:8000"

  playbase-toolbox:
    <<: *playbase-common
    command: ["playbase-cli"]

  playbase-worker:
    <<: *playbase-common
    command: ["playbase-cli", "worker"]

  playbase-beat:
    <<: *playbase-common
    command: ["playbase-cli", "beat"]

  playbase-flower:
    <<: *playbase-common
    command: ["playbase-cli", "flower"]

volumes:
  postgres_data_dev: { }
  postgres_backup_dev: { }
