# Generated by Django 2.0 on 2018-01-28 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='分类名')),
                ('order_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('char_num', models.IntegerField(default=0, verbose_name='字数统计')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='允许评论')),
                ('vote_num', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发表时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_posts', to='yablog.BlogCategory', verbose_name='博文种类')),
            ],
            options={
                'verbose_name': '博客博文',
                'verbose_name_plural': '博客博文',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='标签名')),
                ('order_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='tags_posts', to='yablog.BlogTag', verbose_name='标签'),
        ),
    ]
